// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID              int64
	Token           string
	IndicatorCode   string
	Operator        string
	Threshold       float64
	WebhookUrl      string
	Active          bool
	LastTriggeredAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type Indicator struct {
	Code        string
	Name        string
	Unit        string
	Description string
	Cadence     string
}

type IndicatorValue struct {
	IndicatorCode string
	Date          time.Time
	Value         float64
	FetchedAt     pgtype.Timestamptz
}

type SyncRun struct {
	ID                int64
	Source            string
	StartedAt         pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
	Status            string
	IndicatorsUpdated int32
	Error             *string
}
