// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (token, indicator_code, operator, threshold, webhook_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, token, indicator_code, operator, threshold, webhook_url, active, last_triggered_at, created_at
`

type CreateAlertParams struct {
	Token         string
	IndicatorCode string
	Operator      string
	Threshold     float64
	WebhookUrl    string
}

// El token opaco lo genera la app (crypto/rand); la webhook_url llega ya
// validada (anti-SSRF, SAD §8). active nace true; el DELETE borra la fila.
func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.Token,
		arg.IndicatorCode,
		arg.Operator,
		arg.Threshold,
		arg.WebhookUrl,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.IndicatorCode,
		&i.Operator,
		&i.Threshold,
		&i.WebhookUrl,
		&i.Active,
		&i.LastTriggeredAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAlertByToken = `-- name: DeleteAlertByToken :execrows
DELETE FROM alerts
WHERE token = $1
`

func (q *Queries) DeleteAlertByToken(ctx context.Context, token string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAlertByToken, token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishSyncRun = `-- name: FinishSyncRun :exec
UPDATE sync_runs
SET finished_at        = now(),
    status             = $1,
    indicators_updated = $2,
    error              = $3
WHERE id = $4
`

type FinishSyncRunParams struct {
	Status            string
	IndicatorsUpdated int32
	Error             *string
	ID                int64
}

func (q *Queries) FinishSyncRun(ctx context.Context, arg FinishSyncRunParams) error {
	_, err := q.db.Exec(ctx, finishSyncRun,
		arg.Status,
		arg.IndicatorsUpdated,
		arg.Error,
		arg.ID,
	)
	return err
}

const getAlertByToken = `-- name: GetAlertByToken :one
SELECT id, token, indicator_code, operator, threshold, webhook_url, active, last_triggered_at, created_at
FROM alerts
WHERE token = $1
`

func (q *Queries) GetAlertByToken(ctx context.Context, token string) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlertByToken, token)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.IndicatorCode,
		&i.Operator,
		&i.Threshold,
		&i.WebhookUrl,
		&i.Active,
		&i.LastTriggeredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getIndicator = `-- name: GetIndicator :one
SELECT code, name, unit, description, cadence
FROM indicators
WHERE code = $1
`

func (q *Queries) GetIndicator(ctx context.Context, code string) (Indicator, error) {
	row := q.db.QueryRow(ctx, getIndicator, code)
	var i Indicator
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Unit,
		&i.Description,
		&i.Cadence,
	)
	return i, err
}

const historyByRange = `-- name: HistoryByRange :many
SELECT indicator_code, date, value
FROM indicator_values
WHERE indicator_code = $1
  AND date >= $2
  AND date <= $3
ORDER BY date
`

type HistoryByRangeParams struct {
	IndicatorCode string
	FromDate      time.Time
	ToDate        time.Time
}

type HistoryByRangeRow struct {
	IndicatorCode string
	Date          time.Time
	Value         float64
}

func (q *Queries) HistoryByRange(ctx context.Context, arg HistoryByRangeParams) ([]HistoryByRangeRow, error) {
	rows, err := q.db.Query(ctx, historyByRange, arg.IndicatorCode, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistoryByRangeRow
	for rows.Next() {
		var i HistoryByRangeRow
		if err := rows.Scan(&i.IndicatorCode, &i.Date, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestValue = `-- name: LatestValue :one
SELECT indicator_code, date, value
FROM indicator_values
WHERE indicator_code = $1
ORDER BY date DESC
LIMIT 1
`

type LatestValueRow struct {
	IndicatorCode string
	Date          time.Time
	Value         float64
}

// La PK (code, date) resuelve esto con un backward scan: sin índice extra.
func (q *Queries) LatestValue(ctx context.Context, indicatorCode string) (LatestValueRow, error) {
	row := q.db.QueryRow(ctx, latestValue, indicatorCode)
	var i LatestValueRow
	err := row.Scan(&i.IndicatorCode, &i.Date, &i.Value)
	return i, err
}

const listActiveAlertsByCode = `-- name: ListActiveAlertsByCode :many
SELECT id, token, indicator_code, operator, threshold, webhook_url, active, last_triggered_at, created_at
FROM alerts
WHERE indicator_code = $1
  AND active
ORDER BY id
`

// Solo las activas: usa el índice parcial alerts_active_by_indicator.
func (q *Queries) ListActiveAlertsByCode(ctx context.Context, indicatorCode string) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listActiveAlertsByCode, indicatorCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.IndicatorCode,
			&i.Operator,
			&i.Threshold,
			&i.WebhookUrl,
			&i.Active,
			&i.LastTriggeredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIndicators = `-- name: ListIndicators :many
SELECT code, name, unit, description, cadence
FROM indicators
ORDER BY code
`

func (q *Queries) ListIndicators(ctx context.Context) ([]Indicator, error) {
	rows, err := q.db.Query(ctx, listIndicators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Indicator
	for rows.Next() {
		var i Indicator
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Unit,
			&i.Description,
			&i.Cadence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlertTriggered = `-- name: MarkAlertTriggered :exec
UPDATE alerts
SET last_triggered_at = now()
WHERE id = $1
`

func (q *Queries) MarkAlertTriggered(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markAlertTriggered, id)
	return err
}

const previousValue = `-- name: PreviousValue :one
SELECT indicator_code, date, value
FROM indicator_values
WHERE indicator_code = $1
  AND date < $2
ORDER BY date DESC
LIMIT 1
`

type PreviousValueParams struct {
	IndicatorCode string
	Date          time.Time
}

type PreviousValueRow struct {
	IndicatorCode string
	Date          time.Time
	Value         float64
}

// El valor inmediatamente anterior a una fecha: la otra mitad de la semántica
// de cruce de las alertas (ADR-006) — se dispara cuando el valor nuevo
// satisface la condición y el anterior no.
func (q *Queries) PreviousValue(ctx context.Context, arg PreviousValueParams) (PreviousValueRow, error) {
	row := q.db.QueryRow(ctx, previousValue, arg.IndicatorCode, arg.Date)
	var i PreviousValueRow
	err := row.Scan(&i.IndicatorCode, &i.Date, &i.Value)
	return i, err
}

const startSyncRun = `-- name: StartSyncRun :one
INSERT INTO sync_runs (source, status)
VALUES ($1, 'running')
RETURNING id
`

func (q *Queries) StartSyncRun(ctx context.Context, source string) (int64, error) {
	row := q.db.QueryRow(ctx, startSyncRun, source)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const sweepOrphanSyncRuns = `-- name: SweepOrphanSyncRuns :execrows
UPDATE sync_runs
SET finished_at = now(),
    status      = 'error',
    error       = 'huérfano: la instancia murió sin cerrar el run (barrido al boot, AUD-004)'
WHERE status = 'running'
  AND started_at < now() - interval '1 hour'
`

// Barrido de huérfanos (AUD-004): un crash duro (OOM, kill -9) deja runs en
// 'running' para siempre. El umbral de 1 hora protege a una instancia vieja
// legítimamente a mitad de ciclo durante un rolling update (el ciclo más
// largo observado son ~8 min con egress roto, T-004).
func (q *Queries) SweepOrphanSyncRuns(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, sweepOrphanSyncRuns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertValue = `-- name: UpsertValue :execrows

INSERT INTO indicator_values (indicator_code, date, value)
VALUES ($1, $2, $3)
ON CONFLICT (indicator_code, date) DO UPDATE
    SET value = EXCLUDED.value, fetched_at = now()
    WHERE indicator_values.value IS DISTINCT FROM EXCLUDED.value
`

type UpsertValueParams struct {
	IndicatorCode string
	Date          time.Time
	Value         float64
}

// Queries de Faro (SAD §6). sqlc las compila a Go type-safe (ADR-004).
// Regenerar con: sqlc generate
// Upsert por (código, fecha): nunca pisa el histórico, solo corrige el valor
// del mismo día. El WHERE hace que "mismo valor" afecte 0 filas — así el
// scheduler distingue "hubo dato nuevo" de "sin cambios" (ADR-011) sin query
// extra. fetched_at solo se mueve cuando el valor realmente cambió.
func (q *Queries) UpsertValue(ctx context.Context, arg UpsertValueParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertValue, arg.IndicatorCode, arg.Date, arg.Value)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
