// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const finishSyncRun = `-- name: FinishSyncRun :exec
UPDATE sync_runs
SET finished_at        = now(),
    status             = $1,
    indicators_updated = $2,
    error              = $3
WHERE id = $4
`

type FinishSyncRunParams struct {
	Status            string
	IndicatorsUpdated int32
	Error             *string
	ID                int64
}

func (q *Queries) FinishSyncRun(ctx context.Context, arg FinishSyncRunParams) error {
	_, err := q.db.Exec(ctx, finishSyncRun,
		arg.Status,
		arg.IndicatorsUpdated,
		arg.Error,
		arg.ID,
	)
	return err
}

const getIndicator = `-- name: GetIndicator :one
SELECT code, name, unit, description, cadence
FROM indicators
WHERE code = $1
`

func (q *Queries) GetIndicator(ctx context.Context, code string) (Indicator, error) {
	row := q.db.QueryRow(ctx, getIndicator, code)
	var i Indicator
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Unit,
		&i.Description,
		&i.Cadence,
	)
	return i, err
}

const historyByRange = `-- name: HistoryByRange :many
SELECT indicator_code, date, value
FROM indicator_values
WHERE indicator_code = $1
  AND date >= $2
  AND date <= $3
ORDER BY date
`

type HistoryByRangeParams struct {
	IndicatorCode string
	FromDate      time.Time
	ToDate        time.Time
}

type HistoryByRangeRow struct {
	IndicatorCode string
	Date          time.Time
	Value         float64
}

func (q *Queries) HistoryByRange(ctx context.Context, arg HistoryByRangeParams) ([]HistoryByRangeRow, error) {
	rows, err := q.db.Query(ctx, historyByRange, arg.IndicatorCode, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistoryByRangeRow
	for rows.Next() {
		var i HistoryByRangeRow
		if err := rows.Scan(&i.IndicatorCode, &i.Date, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestValue = `-- name: LatestValue :one
SELECT indicator_code, date, value
FROM indicator_values
WHERE indicator_code = $1
ORDER BY date DESC
LIMIT 1
`

type LatestValueRow struct {
	IndicatorCode string
	Date          time.Time
	Value         float64
}

// La PK (code, date) resuelve esto con un backward scan: sin índice extra.
func (q *Queries) LatestValue(ctx context.Context, indicatorCode string) (LatestValueRow, error) {
	row := q.db.QueryRow(ctx, latestValue, indicatorCode)
	var i LatestValueRow
	err := row.Scan(&i.IndicatorCode, &i.Date, &i.Value)
	return i, err
}

const listIndicators = `-- name: ListIndicators :many
SELECT code, name, unit, description, cadence
FROM indicators
ORDER BY code
`

func (q *Queries) ListIndicators(ctx context.Context) ([]Indicator, error) {
	rows, err := q.db.Query(ctx, listIndicators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Indicator
	for rows.Next() {
		var i Indicator
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Unit,
			&i.Description,
			&i.Cadence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startSyncRun = `-- name: StartSyncRun :one
INSERT INTO sync_runs (source, status)
VALUES ($1, 'running')
RETURNING id
`

func (q *Queries) StartSyncRun(ctx context.Context, source string) (int64, error) {
	row := q.db.QueryRow(ctx, startSyncRun, source)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertValue = `-- name: UpsertValue :execrows

INSERT INTO indicator_values (indicator_code, date, value)
VALUES ($1, $2, $3)
ON CONFLICT (indicator_code, date) DO UPDATE
    SET value = EXCLUDED.value, fetched_at = now()
    WHERE indicator_values.value IS DISTINCT FROM EXCLUDED.value
`

type UpsertValueParams struct {
	IndicatorCode string
	Date          time.Time
	Value         float64
}

// Queries de Faro (SAD §6). sqlc las compila a Go type-safe (ADR-004).
// Regenerar con: sqlc generate
// Upsert por (código, fecha): nunca pisa el histórico, solo corrige el valor
// del mismo día. El WHERE hace que "mismo valor" afecte 0 filas — así el
// scheduler distingue "hubo dato nuevo" de "sin cambios" (ADR-011) sin query
// extra. fetched_at solo se mueve cuando el valor realmente cambió.
func (q *Queries) UpsertValue(ctx context.Context, arg UpsertValueParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertValue, arg.IndicatorCode, arg.Date, arg.Value)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
